backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "writing"
    label: "Writing"
    folder: "src/pages/writing"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      # - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      # - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      # - { label: "Tags", name: "tags", widget: "list" }
  - name: "portfolio"
    label: "portfolio"
    folder: "src/pages/portfolio"
    create: true
    flug: "{{name}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "portfolio-page",
        }
      - { label: "Portfolio Name", name: "name", widget: "string" }
      - {
          label: "Portfolio Type",
          name: "type",
          widget: "select",
          options: ["Crypto Master Fund", "Non-Fungible Collective"]
        }
      - { label: "Portfolio Image", name: "image", widget: image }